### ISSUE TITLE
React Life Cycle Methods W1D5

### ISSUE THREAD

**Issue by nmatison** [appacademy/job-search-guide#8]
This is regarding the link to the React Life Cycle Methods found on [W1D5's](https://github.com/appacademy/job-search-guide/blob/master/weeks/01/05.md) miscellaneous section. Although the article is incredibly well-written, it is a bit out-dated in that the React team is deprecating a few of the life cycle methods mentioned by the author as they encourage "unsafe coding practices":
+ componentWillMount
+ componentWillReceiveProps
+ componentWillUpdate

and adding in:

+ getDerivedStateFromProps 
+ getSnapshotBeforeUpdate.

in order to try to promote better coding practice. This is as of March 2018.

The following blog post contains information on how to make the switch and why they decided to make this move: https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html

I'd submit a pull request myself, but I'm not sure how best to present the information? Maybe a link to the  original life-cycle blog post and then a note about the deprecation and then a link to this other blog post that explains why and how to make the switch? I feel it is important to know as employers may want to see if we are up to date with our React knowledge.

**Comment by rkoron007** [comment]
Good Point! I've added it in for the online platform - thank you for the great suggestion!
